baseurl = "https://seanny123.github.io/"
languageCode = "en-us"
title = "Voyageur Technologique"
theme = "hugo-tufte-dark"
contentdir = "content"
layoutdir = "layouts"

[author]
  name = "Sean Aubin"

[params]
  copyright = "Licensed under <a href='https://creativecommons.org/licenses/by-nc/4.0/'>Creative Commons 4.0 Attribution & Non-Commercial</a>"
  copyrightHolder = "Sean Aubin"
    showPoweredBy = true

# -----------------------------------------------------------------------
# Navigation menu 
# -----------------------------------------------------------------------
[[menu.nav]]
  name = "Home"
  pre = "<i class='fa fa-home fa-lg'></i> "
  weight = -110 
  identifier = "home"
  url = "/"
[[menu.nav]]
  name = "Posts"
  pre = "<i class='fa fa-book fa-lg'></i> "
  weight = -100 
  identifier = "posts"
  url = "/post"
[[menu.nav]]
  name = "Categories"
  pre = "<i class='fa fa-tags fa-lg'></i> "
  weight = -90 
  identifier = "categories"
  url = "/categories"

# -----------------------------------------------------------------------
# Footer menu 
# -----------------------------------------------------------------------
[[menu.footer]]
  name = ""
  pre = "<i class='fa fa-github fa-2x'></i> "
  weight = -100 
  identifier = "github"
  url = "https://github.com/Seanny123"
[[menu.footer]]
  name = ""
  pre = "<i class='fa fa-twitter fa-2x'></i> "
  weight = -90 
  identifier = "twitter"
  url = "https://twitter.com/voyageur_techno"
